### PR TITLE
Running Sum of Array #189

### PR DESCRIPTION
**Pull request by SwatiSrivastava216**
#189 
Write a program that reads an array of nums and outputs the running sum of in the given array of numbers.

Sample Input:
[1,2,3,4]

Sample Output:
[1,3,6,10]

Explanation:
Running sum is obtained as [1, 1+2, 1+2+3, 1+2+3+4]

### CODE REVIEW

**Comment by SwatiSrivastava216** [comment]
#189 
Running Sum of Array

**Comment by avinash201199** [comment]
pull request merged, now close the issue :)
follow for more

note- only 2 pr are accepted per day on a same repo

**Comment by SwatiSrivastava216** [comment]
Official Hacktoberfest page shows that this is an excluded project for hacktoberfest.

**Comment by avinash201199** [comment]
They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)

**Comment by avinash201199** [comment]
> Official Hacktoberfest page shows that this is an excluded project for hacktoberfest.

sorry , you can contribute to other repo

**Pull request merged**
