### PR TITLE
Doubly linked list #182

### PR DESCRIPTION
**Pull request by Mohamed-Ayaan358**
Issue Number: #182

This is my implementation for the doubly linked list. It posses the ability to destroy the list as well as initialise it.

The main processes of insert and delete, as well as display, are present.

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
Yes, I have been assigned this pull request and I have updated the files respectively.

You can merge the files now.  #182  @avinash201199

**Comment by avinash201199** [comment]
@Mohamed-Ayaan358  write full name of the program .

**Comment by Mohamed-Ayaan358** [comment]
Done

**Comment by avinash201199** [comment]
@Mohamed-Ayaan358  closing this pr because all the changes you have made was reflected on the pr which I have merged right now so make only obe pr at a time

**Comment by Mohamed-Ayaan358** [comment]
So am i allowed to make another pull request or is that it ?

**Pull request closed without merging**
