### PR TITLE
A short solution in Java to return reverse of an Array (Hacktober Fes…

### PR DESCRIPTION
**Pull request by ishitaojha**
#8 

A short and neat solution in Java to return the reverse of an input array with time complexity O(n)

### CODE REVIEW

**Comment by avinash201199** [comment]
@ishitaojha 
Thank you for contribution , wll accept your pull request on 1st october for successful count.

**Comment by avinash201199** [comment]
@ishitaojha please check your profile on the official website of hacktoberfest , is it showing successful pr ?

**Comment by ishitaojha** [comment]
No only the readme issue that I have updated is showing over there ( Hacktober Banner one)

**Comment by avinash201199** [comment]
> No only the readme issue that I have updated is showing over there ( Hacktober Banner one)

I guess it will take time to refresh , informe me later.

**Pull request merged**
