### PR TITLE
Rotate Array [Code] with explanation

### PR DESCRIPTION
**Pull request by ritika728**
I have written code with proper explanation on Left Rotation of an array in C++.

### CODE REVIEW

**Comment by ritika728** [comment]
@avinash201199 Please review!

**Comment by avinash201199** [comment]
> @avinash201199 Please review!

will accept your pr after 12:00 am

**Comment by ritika728** [comment]
> > @avinash201199 Please review!
> 
> will accept your pr after 12:00 am

Thank you!

**Comment by ritika728** [comment]
@avinash201199 Please merge!

**Comment by avinash201199** [comment]
@ritika728 now you can contribute to this repo by adding resume https://github.com/avinash201199/Hacktoberfest-Guide

**Pull request merged**
