### PR TITLE
Sliding Window Maximum #229

### PR DESCRIPTION
**Pull request by Rohit5152**
Hey I have solved my issue please merge it
if any conflicts please let me know

### CODE REVIEW

**Comment by Rohit5152** [comment]
Thanks

**Comment by avinash201199** [comment]
@Rohit5152  delete extra file , you have  added 4 files of 2 program , delete 2 extra file

**Comment by Rohit5152** [comment]
> @Rohit5152 delete extra file , you have added 4 files of 2 program , delete 2 extra file

Okay sir i will make another pull request

**Comment by Rohit5152** [comment]
> @Rohit5152 delete extra file , you have added 4 files of 2 program , delete 2 extra file

Bhai i have removed duplicate files please now merge it
I hope so. please

**Comment by avinash201199** [comment]
They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)

**Pull request merged**
