### PR TITLE
#84 Issue Resolution

### PR DESCRIPTION
**Pull request by mukunddeepak**
#84 Issue Resolved!
Hey Avinash,

I have put the code as promised.
Hope to do more in this repo!

Regards,
Mukund Deepak

### CODE REVIEW

**Comment by mukunddeepak** [comment]
@avinash201199 please close pull request

**Comment by mukunddeepak** [comment]
@avinash201199 waiting for review 😄

**Comment by mukunddeepak** [comment]
**Info about the program**:
This is a C program which converts an infix expression to postfix through the implementation of stacks.
Example: 2*3+1 -> 23*1+

**Comment by avinash201199** [comment]
pull request merged, you can also contribute to other repo's-https://github.com/avinash201199/Hacktoberfest-Guide

Note- only 2 pr per day on a single repo is accepted.

**Pull request merged**
