### PR TITLE
Added Longest Consecutive Sequence

### PR DESCRIPTION
**Pull request by arihantthriwe**
Please check my pull request i have added LongestConsecutiveSequence solution using c++. (DSA-Questions -> Hash Table -> LongestConsecutiveSequence).

Thank You :)

### CODE REVIEW

**Comment by avinash201199** [comment]
@arihantthriwe  you haven't added files properly , please check and correct it .

**Comment by arihantthriwe** [comment]
Hi :) , I have added Description, examples and approach in LongestConsecutiveSequence.
Please check.
Thank You :)

**Comment by arihantthriwe** [comment]
Please specify precisely for which other files you are talking about.
:|

**Comment by avinash201199** [comment]
image

What are these extra files  .DS_Store ?
remove it .

**Comment by arihantthriwe** [comment]
Done.
And thanks for the heads up.
Please Check :)

**Pull request merged**
