### PR TITLE
Painting_the_fence

### PR DESCRIPTION
**Pull request by manognyaa**
Hello sir,

I have added the files, in Images folder I have added the screenshots and also added the code.

Pls kindly accept my pr `@avinash201199` sir ✨

input
,lllll
-

output
lll;

In cpp file I cannot add the ss. So, I am adding here sir.

### CODE REVIEW

**Comment by avinash201199** [comment]
@manognyaa  
Hey, you don't need to add the images, add all the information in code file only.
Please delete the images ,will accept your pr after that .
Thanks :)

**Comment by avinash201199** [comment]
pull request merged , please close the issue now :)
follow for more such repo to contribute

**Comment by manognyaa** [comment]
> pull request merged , please close the issue now :) follow for more such repo to contribute

sure sir. thank you !

**Comment by avinash201199** [comment]
They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)
you can contribute to other repo

**Pull request merged**
