### PR TITLE
Added 3 linked list questions with solution and some explanation in java 

### PR DESCRIPTION
**Pull request by herkura**
Can you review them and merge it on oct 1 😄 ?

### CODE REVIEW

**Comment by avinash201199** [comment]
> Can you review them and merge it on oct 1 😄 ?

sure , till then check other repo's

**Comment by herkura** [comment]
@avinash201199  thx alot ... will definitely look for other repos

**Comment by avinash201199** [comment]
> @avinash201199 thx alot ... will definitely look for other repos

accepted your pr :)

**Comment by herkura** [comment]
@avinash201199 On my hactoberfest's dashboard it is saying that this project is excluded?

**Comment by avinash201199** [comment]
They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)

**Pull request merged**
