### PR TITLE
 length_of_last_word.cpp

### PR DESCRIPTION
**Pull request by srusti610**
Kindly merge.

### CODE REVIEW

**Comment by srusti610** [comment]
Kindly merge.

**Comment by avinash201199** [comment]
@srusti610  add some description on matrix question.

**Comment by srusti610** [comment]
Added description. Kindly merge.

**Comment by avinash201199** [comment]
> Added description. Kindly merge.

They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)

**Pull request merged**
