### PR TITLE
Optimized Longest Common Subsequence (issue #188) C++ (DP) harry6003 

### PR DESCRIPTION
**Pull request by harry6003**
Longest Common Subsequence C++ (DP) harry6003

Medium Level Problem asked in my last interview

### CODE REVIEW

**Comment by harry6003** [comment]
Issue #188 Please review @avinash201199

**Comment by harry6003** [comment]
Issue number #188 Please review and Merge the PR

**Comment by harry6003** [comment]
This is an Optimized Longest Common Subsequence solution , which is having better Time Complexity than previous one.

**Comment by avinash201199** [comment]
pull request merged, now please close the issue, you can also contribute to other repo's-https://github.com/avinash201199/Hacktoberfest-Guide

Note- only 2 pr per day on a single repo is accepted.

**Comment by harry6003** [comment]
Ok Bro. Thanks for Merging

**Pull request merged**
